---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidar-converter-server-lidar-converter-server-ossim-data-pv
spec:
  capacity:
    storage: 16G

  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfs-ossim-data-dev
    server: o2-nfs.private.ossim.io
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidar-converter-server-ossim-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 16G
  volumeName: lidar-converter-server-lidar-converter-server-ossim-data-pv